### ISSUE TITLE
backlinks from elements to guidelines

### ISSUE THREAD

**Issue by kepper** [music-encoding/guidelines#12]
In C'ville, we discussed the potential addition of links from the elementSpecs to all chapters in which the current element is mentioned. However, this is possible only as long as we still have the guidelines in XML, and will go away soon. After that, we need to come up with a mechanism in Travis that identifies these references in the guideline markdown files and inserts that automatically in the HTML version of the elementSpecs (no need to put it in the ODD definitions). We don't have that mechanism in place yet, so there is a certain risk of not being able to reflect the current state of the guideline chapters in the elementSpecs. At the same time, the guidelines aren't moving fast these days. I'm inclined to include those references now, and come up with a maintenance plan for them based on Travis as a second step. Thoughts?

**Comment by lpugin** [comment]
The search is here:
https://music-encoding.github.io/guidelines/search.html

A few search examples:
https://music-encoding.github.io/guidelines/search.html?q=syl
https://music-encoding.github.io/guidelines/search.html?q=rdg
https://music-encoding.github.io/guidelines/search.html?q=scoreDef
https://music-encoding.github.io/guidelines/search.html?q=edition

Of course it does not replace the backlinks.

**Comment by pe-ro** [comment]
This is much better than backlinks, esp. since it cuts down on future maintenance. :grinning: 

Is this using an index of some kind or is a brute force search of the full text?  If the former, how/when is the indexing performed?

**Comment by pe-ro** [comment]
I consider this issue settled, so I'd like to direct attention to https://github.com/music-encoding/music-encoding/issues/454, which I think is much more pressing because it's creating incorrect data.

For example, the description of `<relatedItem>` says that it may occur within

`<perfDuration>`, 
`<bibl>`, 
`<biblScope>`, 
`<creation>`, 
`<extent>`, 
`<genre>`, 
`<imprint>`, 
`<physLoc>`, 
`<recipient>`, 
`<relatedItem>`, 
`<series>`, and 
`<textLang>`, 

when it's actually only allowed within `<bibl>`.

**Comment by kepper** [comment]
I was trying to get rid of those other issues first, and will turn to these structural things now…

**Comment by pe-ro** [comment]
Muchas gracias.
