### ISSUE TITLE
3.1.1.3: PhysDesc not allowed in fileDesc

### ISSUE THREAD

**Issue by axgeertinger** [music-encoding/guidelines#120]
Chapter 3.1.1.3. "Physical Description of the File" should be renamed and the example corrected accordingly (remove physDesc)

**Comment by musicEnfanthen** [comment]
@rieede @doerners May I ask you to check if this is still an issue?

**Comment by riedde** [comment]
yes, the referred chapter 3.1.1.2 has become 3.4.1.2.

Its still an Issue, since the data model has changed (seems like).

The section should be renamed, e.g., "Extent of the File" and Listing 44, as @doerners and already @axgeertinger mentioned, must be reworked (erasing physDesc). I will provide a PR for this.
