### ISSUE TITLE
Relying on SMuFL-Browser

### ISSUE THREAD

**Issue by rettinghaus** [music-encoding/guidelines#146]
We use Edirom's SMuFL-Browser for displaying some glyphs. But what to do, if something's not working like now (https://github.com/Edirom/SMuFL-Browser/issues/3)? Currently mordents aren't displayed: https://music-encoding.org/guidelines/v4/content/cmn.html#cmnOrnamentsMordents
@kepper @bwbohl could/should we use local copys?

**Comment by kepper** [comment]
as @peterstadler points out, this was a broken dependency, which he was able to fix – thanks for that :+1 
I think our first priority should be to fix such issues where they occur, because fallbacks like local copies will need to be reverted manually afterwards – I think there's a risk of cluttering our repo when going there too easily… But nevertheless: Good catch, @rettinghaus :-)

**Comment by th-we** [comment]
@peterstadler The service is down again at the moment.

**Comment by peterstadler** [comment]
@th-we we had some temporary server issues, now it's back up.
