### ISSUE TITLE
missing images

### ISSUE THREAD

**Issue by craigsapp** [music-encoding/guidelines#69]
On the page:

https://music-encoding.org/guidelines/v4/content/usersymbols.html

There are six missing images,such as:

<img width="610" alt="screen shot 2019-02-08 at 3 44 31 am" src="https://user-images.githubusercontent.com/3487289/52467568-f4bfc800-2b53-11e9-887f-e96ada12eeb7.png">

**Comment by bwbohl** [comment]
Figure contents was

```xml
<symbolDef xml:id="userSymbols.triangleSymbol3">
  <line x="0" x2="2.55" y="0" y2="4.25"/>
  <line x="2.55" x2="5.1" y="4.25" y2="0"/>
  <line x="5.1" x2="0.85" y="0" y2="0"/>
</symbolDef>
````
and 

```xml
<symbolDef xml:id="userSymbols.triangleSymbolWithStick">
  <symbol ref="#userSymbols.triangleSymbol3"/>
  <line x="2.55" x2="5.95" y="1.25" y2="3.4"/>
</symbolDef>
```

how should this get back into the guidelines:
a) directly as codeblock as above?
b) via xml snippet in example file?

**Comment by musicEnfanthen** [comment]
It seems that the section uses a wrong include snippet, trying to include (non-existing) figures instead of encoding samples, so

`
{% include figure img="" caption="Definition of a triangle percussion symbol using graphic primitives" %} `

instead of

`{% include mei example="usersymbols/usersymbols-sampleXXX.xml" valid="" %}`

The encoding samples are here: https://github.com/music-encoding/guidelines/tree/master/_includes/v4/examples/usersymbols

**Comment by bwbohl** [comment]
@musicEnfanthen thx for spotting this, nevertheless the figures had been included in previous versions of the guidelines and I think they should be reintroduced, best both, code and figure. I'll see what I can do when fixing the new chapter 2 (cf. #81 )

**Comment by musicEnfanthen** [comment]
Fully agree

**Comment by rettinghaus** [comment]
see https://music-encoding.org/guidelines/v4/content/shared.html#usersymbolsReusableSymbols
